### ISSUE TITLE
Add Trident implementation

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/lsqb#53]
Paper: https://arxiv.org/abs/2001.09078
Repository: https://github.com/karmaresearch/trident/

**Comment by kuzeko** [comment]
I've pushed my WIP branch
https://github.com/ldbc/lsqb/tree/trident

they fixed one issue on the COUNT/COUNT DISTINCT but other SegFault appear (to be investigated)

**Comment by szarnyasg** [comment]
Oops, I mixed up this issue with #52. I wanted to close that one.

**Comment by szarnyasg** [comment]
I merged `main` into `trident` and revamped the README. I think we're close to getting to this work, so it would be great if we could follow up with the Trident developers (who seem to be quite [active](https://github.com/karmaresearch/trident/commit/2d9ba73a57af9bb72ee6b90b4635cd94cf5aa166)) soon.
