### ISSUE TITLE
'No space left on device' errors by Neo4j and Postgres

### ISSUE THREAD

**Issue by eliashoffmann** [ldbc/lsqb#61]
Running the benchmark on neo and pos fails when the current user has limited write permissions to system directories.

### Postgres

Starting the container (without detaching) fails with:
```
fixing permissions on existing directory /var/lib/postgresql/data ... ok
initdb: error: could not create directory "/var/lib/postgresql/data/pg_wal": No space left on device
initdb: removing contents of data directory "/var/lib/postgresql/data"
```

### Neo4j

Starting the container works, but loading a dataset throws Exceptions such as:
```
org.neo4j.logging.shaded.log4j.core.appender.AppenderLoggingException: Error writing to stream /logs/debug.log
        at org.neo4j.logging.shaded.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
        at org.neo4j.logging.shaded.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
[...]
Caused by: java.io.IOException: No space left on device
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
```

I found a fix that I will share shortly.

**Comment by szarnyasg** [comment]
Hi @eliashoffmann,

Thanks for reporting this.

I had a similar problem and my fix was to move the Docker directory to a different partition:
https://github.com/ftsrg/cheat-sheets/wiki/Docker#move-docker-data-folder-to-a-different-location

Did you also use this workaround?

Gabor

**Comment by eliashoffmann** [comment]
Hi Gabor,

@PerFuchs and I also moved the docker data folder, but without success. Maybe it would have been required to change some other ownerships/permissions of the folder as well.

I resolved the issue by mounting two volumes to the containers.

**Comment by szarnyasg** [comment]
@eliashoffmann - I tested the PR but it seems the Postgres instance no longer starts.

I removed `--detach` so I see the error message:

```bash
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
Using a mount point directly as the data directory is not recommended.
Create a subdirectory under the mount point.
```

It seems that, ironically, this issue is caused by the `.gitignore` file in the `pos/scratch` directory... 
Trying a workaround in #63.

**Comment by szarnyasg** [comment]
That seemed to have solved it.
