### ISSUE TITLE
Undefined table in q4.sql

### ISSUE THREAD

**Issue by remysucre** [ldbc/lsqb#85]
sql/q4.sql references a table "Message_hasTag_Tag" which is not defined in sql/schema.sql. Should it be Post_hasTag_Tag instead?

**Comment by remysucre** [comment]
In fact, none of the tables used in q4 exist in the schema.

**Comment by szarnyasg** [comment]
@remysucre these are views, defined in [`sql/views.sql`](https://github.com/ldbc/lsqb/blob/main/sql/views.sql). Implementations are also free to define these tables (e.g. `Message_hasTag_Tag`, `Person_likes_Message`, etc.), if they drop the original Post/Comment tables one they populated the Message tables.

**Comment by remysucre** [comment]
Thanks for clarifying!
