### ISSUE TITLE
some bugs when running the kuzu 

### ISSUE THREAD

**Issue by ycluu** [ldbc/lsqb#91]
It seems that in the files of  "load.py" and "client.py" of kuz exist some bugs. In the file "load.py", the line "db = kuzu.database('kuz/scratch/lsqb-database') conn = kuzu.connection(db)" have issue. kuzu doesn't have fuctions "database" and "connection", but have fuctions "Database" and "Connection". And in the file "client.py", there are some similar problems in the line "if results.has_next(): result = results.get_next()"and "db = kuzu.Database('kuz/scratch/lsqb-database') conn = kuzu.Connection(db)".  Maybe there are some changes made to kuzu, which causes the files in kuz don't work?

**Comment by szarnyasg** [comment]
@ycluu
> Maybe there are some changes made to kuzu, which causes the files in kuz don't work?
That's very likely - this benchmark was implemented on a very early version of Kùzu (v0.0.1 or v0.0.2, if I recall correctly). So the code needs to be updated to run with the latest version (v0.1.x).
